### ISSUE TITLE
Adding of other youtube channel for the frontend part

### ISSUE THREAD

**Issue by lavakush07** [sadanandpai/frontend-learning-kit#12]
## We can add Javascript mastery youtube channel in the frontend list part

- [Javascript mastery](https://www.youtube.com/results?search_query=javascript+mastery)
- By through this channel we can learn the frontend frameworks by doing the projects which we can publish it on our resume too..

**Comment by sadanandpai** [comment]
Thanks for the suggestion. Will add it under additional resources.
